# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_registry_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Entry(QtWidgets.QLineEdit):
    def __init__(self, frame: QtWidgets.QFrame):
        super(Entry, self).__init__(frame)
        self.default_text = ""

    def focusInEvent(self, a0: QtGui.QFocusEvent) -> None:
        if self.text() == self.default_text:
            self.clear()
            if "PASSWORD" in self.default_text:
                self.setEchoMode(self.Password)
        super().focusInEvent(a0)

    def focusOutEvent(self, a0: QtGui.QFocusEvent) -> None:
        if self.text() == "":
            self.setText(self.default_text)
            if "PASSWORD" in self.default_text:
                self.setEchoMode(self.Normal)
        super().focusOutEvent(a0)


class Main_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setMinimumSize(QtCore.QSize(800, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QFrame(self.frame)
        self.side_menu.setMinimumSize(QtCore.QSize(50, 0))
        self.side_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.side_menu.setStyleSheet("background-color:rgb(51, 49, 56);\n"
                                     "")
        self.side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SM_menu_frame = QtWidgets.QFrame(self.side_menu)
        self.SM_menu_frame.setMinimumSize(QtCore.QSize(50, 50))
        self.SM_menu_frame.setMaximumSize(QtCore.QSize(50, 50))
        self.SM_menu_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SM_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SM_menu_frame.setObjectName("SM_menu_frame")
        self.SM_menu = QtWidgets.QLabel(self.SM_menu_frame)
        self.SM_menu.setGeometry(QtCore.QRect(5, 5, 40, 40))
        self.SM_menu.setText("")
        self.SM_menu.setPixmap(QtGui.QPixmap("Media/menu-icon50x50.png"))
        self.SM_menu.setScaledContents(True)
        self.SM_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.SM_menu.setObjectName("SM_menu")
        self.verticalLayout_3.addWidget(self.SM_menu_frame)
        self.SM_menu_profile = QtWidgets.QFrame(self.side_menu)
        self.SM_menu_profile.setMinimumSize(QtCore.QSize(50, 50))
        self.SM_menu_profile.setMaximumSize(QtCore.QSize(50, 50))
        self.SM_menu_profile.setStyleSheet("background-image: url(Media/menu-icon.png);\n"
                                           "background-repeat: none\n"
                                           "")
        self.SM_menu_profile.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SM_menu_profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SM_menu_profile.setObjectName("SM_menu_profile")
        self.SM_profile = QtWidgets.QLabel(self.SM_menu_profile)
        self.SM_profile.setGeometry(QtCore.QRect(2, 2, 45, 45))
        self.SM_profile.setText("")
        self.SM_profile.setPixmap(QtGui.QPixmap("Media/profile50x50.png"))
        self.SM_profile.setScaledContents(True)
        self.SM_profile.setAlignment(QtCore.Qt.AlignCenter)
        self.SM_profile.setObjectName("SM_profile")
        self.verticalLayout_3.addWidget(self.SM_menu_profile)
        self.SM_menu_spacing = QtWidgets.QFrame(self.side_menu)
        self.SM_menu_spacing.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SM_menu_spacing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SM_menu_spacing.setObjectName("SM_menu_spacing")
        self.verticalLayout_3.addWidget(self.SM_menu_spacing)
        self.SM_menu_settings = QtWidgets.QFrame(self.side_menu)
        self.SM_menu_settings.setMinimumSize(QtCore.QSize(50, 50))
        self.SM_menu_settings.setMaximumSize(QtCore.QSize(50, 50))
        self.SM_menu_settings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SM_menu_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SM_menu_settings.setObjectName("SM_menu_settings")
        self.SM_setting = QtWidgets.QLabel(self.SM_menu_settings)
        self.SM_setting.setGeometry(QtCore.QRect(5, 5, 40, 40))
        self.SM_setting.setText("")
        self.SM_setting.setPixmap(QtGui.QPixmap("Media/Settings50x50.png"))
        self.SM_setting.setScaledContents(True)
        self.SM_setting.setAlignment(QtCore.Qt.AlignCenter)
        self.SM_setting.setObjectName("SM_setting")
        self.verticalLayout_3.addWidget(self.SM_menu_settings)
        self.horizontalLayout.addWidget(self.side_menu)
        self.main_content = QtWidgets.QFrame(self.frame)
        self.main_content.setMinimumSize(QtCore.QSize(650, 600))
        self.main_content.setMaximumSize(QtCore.QSize(750, 16777215))
        self.main_content.setStyleSheet("background-color: rgb(13, 0, 0);")
        self.main_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_content.setObjectName("main_content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_content)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Error_Area = QtWidgets.QFrame(self.main_content)
        self.Error_Area.setMinimumSize(QtCore.QSize(0, 100))
        self.Error_Area.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Error_Area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Error_Area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Error_Area.setObjectName("Error_Area")
        self.gridLayout = QtWidgets.QGridLayout(self.Error_Area)
        self.gridLayout.setContentsMargins(125, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.EA_Box = QtWidgets.QFrame(self.Error_Area)
        self.EA_Box.setMinimumSize(QtCore.QSize(500, 90))
        self.EA_Box.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.EA_Box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.EA_Box.setObjectName("EA_Box")
        self.EAB_label = QtWidgets.QLabel(self.EA_Box)
        self.EAB_label.setGeometry(QtCore.QRect(0, 0, 500, 90))
        self.EAB_label.setStyleSheet("background-color: rgb(162, 44, 41);\n"
                                     "border:0px outset rgb(199, 53, 51);\n"
                                     "border-radius: 10px;\n"
                                     "font: 75 22pt \"Arial Narrow\";")
        self.EAB_label.setMidLineWidth(0)
        self.EAB_label.setAlignment(QtCore.Qt.AlignCenter)
        self.EAB_label.setObjectName("EAB_label")
        self.pushButton = QtWidgets.QPushButton(self.EA_Box)
        self.pushButton.setGeometry(QtCore.QRect(475, 30, 20, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "background-color: rgb(162, 44, 41);\n"
                                      "border-radius: 5px;\n"
                                      "font: 14pt \"Arial Narrow\";\n"
                                      "}\n"
                                      "QPushButton::hover{\n"
                                      "background-color: rgba(236, 20, 0, 50);\n"
                                      "border: 0px solid rgb(186, 18, 0);\n"
                                      "}\n"
                                      "QPushButton::pressed{\n"
                                      "color: rgb(238, 240, 242);\n"
                                      "background-color: rgb(53, 59, 60);\n"
                                      "}\n"
                                      "\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.EA_Box, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.Error_Area)
        self.Profile_Area = QtWidgets.QFrame(self.main_content)
        self.Profile_Area.setMinimumSize(QtCore.QSize(0, 275))
        self.Profile_Area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Profile_Area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile_Area.setMidLineWidth(0)
        self.Profile_Area.setObjectName("Profile_Area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Profile_Area)
        self.verticalLayout_2.setContentsMargins(262, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PA_Icon = QtWidgets.QFrame(self.Profile_Area)
        self.PA_Icon.setMinimumSize(QtCore.QSize(220, 220))
        self.PA_Icon.setMaximumSize(QtCore.QSize(220, 221))
        self.PA_Icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PA_Icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PA_Icon.setObjectName("PA_Icon")
        self.PAI_avatar = QtWidgets.QLabel(self.PA_Icon)
        self.PAI_avatar.setGeometry(QtCore.QRect(0, 0, 220, 220))
        self.PAI_avatar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PAI_avatar.setAutoFillBackground(False)
        self.PAI_avatar.setStyleSheet("QLabel{\n"
                                      "border-radius: 100px;\n"
                                      "border: 4px solid rgb(65, 71, 121);\n"
                                      "background-image: url(Media/Default_avatar.png);\n"
                                      "background-repeat: none;\n"
                                      "}\n"
                                      "QLabel::hover{\n"
                                      "background-image: url(Media/Default_avatar_with_camera.png);\n"
                                      "}\n"
                                      "")
        self.PAI_avatar.setText("")
        self.PAI_avatar.setScaledContents(False)
        self.PAI_avatar.setWordWrap(False)
        self.PAI_avatar.setObjectName("PAI_avatar")
        self.verticalLayout_2.addWidget(self.PA_Icon)
        self.PA_Profile = QtWidgets.QFrame(self.Profile_Area)
        self.PA_Profile.setMinimumSize(QtCore.QSize(220, 40))
        self.PA_Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PA_Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PA_Profile.setObjectName("PA_Profile")
        self.lineEdit = Entry(self.PA_Profile)
        self.lineEdit.setGeometry(QtCore.QRect(0, 5, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
                                    "border: 0px;\n"
                                    "color: rgba(195, 195, 195, 255);\n"
                                    "}\n"
                                    "QLineEdit::focus{\n"
                                    "border-top: 1px solid rgba(65, 71, 121, 150);\n"
                                    "border-bottom: 1px solid rgba(65, 71, 121, 150);\n"
                                    "border-radius: 4px\n"
                                    "}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.PA_Profile)
        self.verticalLayout.addWidget(self.Profile_Area)
        self.Password_Field = QtWidgets.QFrame(self.main_content)
        self.Password_Field.setMinimumSize(QtCore.QSize(0, 225))
        self.Password_Field.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Password_Field.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Password_Field.setObjectName("Password_Field")
        self.PF_username = Entry(self.Password_Field)
        self.PF_username.setGeometry(QtCore.QRect(155, 40, 440, 40))
        self.PF_username.setStyleSheet("QLineEdit{\n"
                                             "background-color: rgb(22, 23, 27);\n"
                                             "border-radius: 15px;\n"
                                             "color: rgba(195, 195, 195, 255);\n"
                                             "}\n"
                                             "QLineEdit::focus{\n"
                                             "border: 2px solid rgba(104, 116, 232);\n"
                                             "}")
        self.PF_username.setObjectName("PF_username")
        self.PF_password_submit = QtWidgets.QPushButton(self.Password_Field)
        self.PF_password_submit.setGeometry(QtCore.QRect(430, 140, 161, 35))
        self.PF_password_submit.setStyleSheet("QPushButton{\n"
                                              "color : rgb(238, 240, 242);\n"
                                              "background-color:rgb(62, 146, 204);\n"
                                              "border-color: rgb(22, 23, 27);\n"
                                              "border-radius: 10px;\n"
                                              "border: 0px;\n"
                                              "}\n"
                                              "QPushButton::hover{\n"
                                              "background-color: rgb(74, 198, 255);\n"
                                              "color :rgb(255, 255, 255);\n"
                                              "}\n"
                                              "QPushButton::pressed{\n"
                                              "background-color: rgb(35, 30, 52);\n"
                                              "color: rgb(195, 195, 195);\n"
                                              "}")
        self.PF_password_submit.setObjectName("PF_password_submit")
        self.PF_password = Entry(self.Password_Field)
        self.PF_password.setGeometry(QtCore.QRect(155, 90, 440, 40))
        self.PF_password.setStyleSheet("QLineEdit{\n"
                                                     "background-color: rgb(22, 23, 27);\n"
                                                     "border-radius: 15px;\n"
                                                     "color: rgba(195, 195, 195, 255);\n"
                                                     "}\n"
                                                     "QLineEdit::focus{\n"
                                                     "border: 2px solid rgba(104, 116, 232);\n"
                                                     "}")
        self.PF_password.setObjectName("PF_password_entry_confirm")
        self.checkBox = QtWidgets.QCheckBox(self.Password_Field)
        self.checkBox.setGeometry(QtCore.QRect(165, 148, 251, 17))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.Password_Field, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.main_content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EAB_label.setText(_translate("MainWindow", "ERROR LABEL"))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.lineEdit.setText(_translate("MainWindow", "{Profile_name}"))
        self.lineEdit.default_text = '{Profile_name}'
        self.PF_password_submit.setText(_translate("MainWindow", "Submit"))
        self.PF_password.setText(_translate("MainWindow", "    PASSWORD"))
        self.PF_password.default_text = '    PASSWORD'
        self.PF_username.setText(_translate("MainWindow", "    USERNAME"))
        self.PF_username.default_text = "    USERNAME"
        self.checkBox.setText(_translate("MainWindow", "Keep me connected"))
